app/games/session/models/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, DateField, DateTimeField, SelectMultipleField, FileField, \
    RadioField
from wtforms.validators import (DataRequired,
                                Email,
                                EqualTo,
                                Length)


class AddSession(FlaskForm):
    """Album Edit Form."""
    # title = StringField("Title", validators=[DataRequired()])
    # release = DateField("Released_in", format='%Y', validators=[DataRequired()])
    # img = FileField("Image")
    # parent = SelectField("Parent", coerce=int, choices=[], validators=[DataRequired()])
    # artist = SelectField("Artist", coerce=int, choices=[], validators=[DataRequired()])
    # genres = SelectMultipleField("Genders", coerce=int, choices=[], validators=[DataRequired()])
    day =  DateField("Jour", validators=[DataRequired()])
    timeB = DateTimeField("Heure début", format='%H:%M', validators=[DataRequired()])
    timeE = DateTimeField("Heure fin", format='%H:%M', validators=[DataRequired()])
    submit = SubmitField('Sauvegarder')

class SessionSearchForm(FlaskForm):
    sessions_hint = StringField("Nom d'une session", id='search-input', render_kw={
        'class': 'form-control',
        'placeholder': 'Rechercher des sessions en fonction du ...',
        'aria-describedby': 'search-buttons'
    })
    display_search_type = SelectField('Type', choices=[('title',"Nom d'un des jeux"),('date',"Date de la session")], render_kw={'class': 'inline-select'})
    display_search_parameter = RadioField('Catégorie de la recherche : ', choices=
        [(None, "Afficher toutes les sessions"),
            ('UPCOMING',"Afficher uniquement les sessions à venir"),
            ('PASSED',"Afficher uniquement les sessions terminées")
        ])
    sort_order = SelectField('Ordre de tri : ', choices=[
        ('mostRecent', 'Plus récents'),
        ('mostAncient', 'Plus vieux')
    ], render_kw={'class': 'custom-select inline-select'})

app/games/session/models/session_tools.py
from flask import request
from app.models import Session, TimeSlot
from app.games.jeux.models.jeux_tools import get_sort_order, get_search_type, get_search_parameter
import datetime

TITLES = {"UPCOMING": "Sessions à venir", "PASSED": "Sessions terminées"}
DEFAULT_TITLE = "Toutes les sessions"

def get_sessions_payload(user, form, page):
    """
    :param user: A instance of a user
    :return: a dict that contains every keys used for the sessions view
    """
    payload = dict()

    # Save those informations to display them when changing page
    form.display_search_parameter.data = get_search_parameter(form.display_search_parameter.data)
    form.sort_order.data = get_sort_order(form.sort_order.data)
    form.display_search_type.data = get_search_type(form.display_search_type.data)
    form.sessions_hint.data = get_search_session(form.sessions_hint.data)

    # If no hint was typed change search type back to game search (avoid crash)
    if not form.sessions_hint.data:
        form.display_search_type.data = "title"

    # We want to keep those informations to be able to show them on the next page
    payload["form"]=form

    # We want to obtain the sessions list that corresponds to what the user asked for
    payload["sessions"] = user.sessions_search_with_pagination(form.sessions_hint.data, form.display_search_type.data, form.display_search_parameter.data, page, 20, form.sort_order.data)

    return payload

def get_search_session(session_hint):
    """
    :param session_hint: suspected session_hint
    :return: searched session_hint
    """
    if session_hint is None:
        session_hint = ""
    return request.args.get('sessions', session_hint, type=str)


def add_session_form(form):
    """
    Create the new objects related to the new organized session
    :return: if the session can be added, return the id of the session, else return False
    """
    date = form.day.data
    timeB = form.timeB.data
    timeE = form.timeE.data

    is_ok = True
    # check format day
    if date is None:
        is_ok = False
        flash("Le format de la date ne correspond pas à AAAA-MM-JJ et/ou le numéro du mois (1-12) et/ou du jour(1-29/30/31 selon le mois) est incorrecte", "warning")

    # check format timeB
    if timeB is None:
        is_ok = False
        flash("Le format de l'heure de début ne correspond pas à HH:MM, et/ou le numéro de l'heure (0-23) et/ou le nombre de minutes (0-59) est incorecte", "warning")

    # check format timeE
    if timeE is None:
        is_ok = False
        flash("Le format de l'heure de fin ne correspond pas à HH:MM, et/ou le numéro de l'heure (0-23) et/ou le nombre de minutes (0-59) est incorecte", "warning")

    if is_ok:
        timeB.replace(second=0)
        timeE.replace(second=0)

        datetimeform = date.isoformat()+"T"+timeB.strftime('%H:%M:%S')

        actual = datetime.datetime.now().replace(microsecond = 0).isoformat() #give a string in ISO 8601 : "YYYY-MM-DDTHH:MM:SS"

        if actual > datetimeform:
            is_ok = False
            flash("Vous ne pouvez pas créer une session pour une date antérieur à aujoud'hui", "warning")
            return False

    else:
        timeout = datetime.date(year=date.year, month=date.month, day=date.day+2)

        timeslot = TimeSlot(timeB.strftime('%H:%M:%S'), timeE.strftime('%H:%M:%S'), date.isoformat())
        # timeslot.add_to_db()
        session = Session(0,timeout.strftime('%Y-%m-%d %H:%M:%S'),1)
        # session.add_to_db()

        return session.id

app/games/session/__init__.py
from flask import Blueprint

session = Blueprint("session", __name__,
                    template_folder="templates")

from . import views

app/games/session/views.py
from app.games.jeux.models.jeux_tools import get_numero_page
from sqlalchemy.sql.functions import current_user
from app.games.session.models.session_tools import get_sessions_payload
from flask import render_template, flash, request, redirect, url_for
from flask_login import login_required, current_user
from .models.forms import AddSession, SessionSearchForm
import datetime
from . import session as session_bp
from app.models import Session, TimeSlot
from .models.session_tools import TITLES, DEFAULT_TITLE, get_sessions_payload, add_session_form


@session_bp.route('/sessions', methods=['GET', 'POST'])
@login_required
def sessions():
    """
    Render the sessions template on the /sessions route
    """
    form = SessionSearchForm()
    page = get_numero_page()
    payload = get_sessions_payload(current_user, form, page)

    # Change title of the page in function of search_parameter
    title = TITLES.get(payload.get("search_parameter"), DEFAULT_TITLE)

    return render_template('sessions.html',
                            stylesheet='users',
                            title=title,
                            now=datetime.datetime.now(),
                            **payload)


@session_bp.route('/session/<int:session_id>', methods=['GET', 'POST'])
@login_required
def session(session_id):
    """
    Render the session template on the /session route
    """
    session = Session.from_id(session_id)
    return render_template('session.html',
                            stylesheet='session',
                            session = session,
                            games=session.get_games(),
                            players=session.get_players(),
                            users_data = current_user.users_search_with_pagination("", False, False, per_page=15))


@session_bp.route('/addplayer_tosession/<int:session_id>', methods=['GET', 'POST'])
@login_required
def add_player(session_id):
    """
    Render the session template on the /session route
    """
    session = Session.from_id(session_id)
    return render_template('add_player.html', stylesheet='session', session = session)


@session_bp.route('/addgame_tosession/<int:session_id>', methods=['GET', 'POST'])
@login_required
def add_game(session_id):
    """
    Render the session template on the /session route
    """
    session = Session.from_id(session_id)
    return render_template('add_player.html', stylesheet='session', session = session)


@session_bp.route('/organize_session', methods=['GET', 'POST'])
@login_required
def organize_session():
    """
    Render the organize_session template on the /organize_session route
    """

    # get_flashed_messages()
    form = AddSession()

    if request.method == "POST":
        if add_session_form(form):
            return redirect(url_for('session.session',session_id=1))
        else:
            return redirect(url_for("session.organize_session"))
    else:
        return render_template('organize_session.html', stylesheet='organize_session', form=form, dest="session.organize_session")

app/games/session/templates/organize_session.html
{% extends "index.html" %}
{% block main %}
<main class="container-fluid mt-auto mb-auto my-auto">
    <form role="form" method="POST" enctype="multipart/form-data" , {% if id == -1 %} action="{{ url_for(dest) }}" {% else %} action="{{ url_for(dest) }}" {% endif %} class="form-signin col-md-6 col-sm-12">
        {{ form.hidden_tag() }}

        {{ super() }}

        <p>Le format du jour est : AAAA-MM-JJ</p>

        <div class="form-group ">
            <label for="" class="col-sm-2 control-label">
                {{ form.day.label }}
            </label>
            <div class="col-sm-10">
                {{ form.day(placeholder = "Day",type="text", class_="form-control", required="True") }}
            </div>
        </div>

        <p>Le format du jour est : HH:MM</p>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">
                {{ form.timeB.label }}
            </label>
            <div class="col-sm-10">
                {{ form.timeB(placeholder = "Heure début", class_="form-control", required="True") }}
            </div>
        </div>

        <div class="form-group">
            <label for="" class="col-sm-2 control-label">
                {{ form.timeE.label }}
            </label>
            <div class="col-sm-10">
                {{ form.timeE(placeholder = "Heure début", class_="form-control", required="True") }}
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset col-sm-10">
                <button class="my-2 btn btn-secondary" onclick="history.go(-1)">Retour</button>
                {{ form.submit(class_="btn btn-black") }}
            </div>
        </div>
    </form>
</main>
{% endblock %}

app/games/session/templates/session.html
{% extends "index.html" %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{{ url_for("static", filename="css/custom-buttons.css") }}">
<main class="container-fluid col-9 mx-auto my-auto">
  <div class="text-center mb-5">
    <h2>Session du {{ session.timeslot.day.strftime("%A %d %B %Y") }}</h2>
    <h3>De {{ session.timeslot.beginning.strftime("%H:%M") }} à {{ session.timeslot.end.strftime("%H:%M") }}</h3>
  </div>
    <div class="d-flex flex-row justify-content-center align-items-center mx-auto mb-5 col-8">
        <button class="btn mr-3 col-3 text-white"
                onclick="window.location.href='{{ url_for("session.add_player", session_id=session.id) }}';">
            Ajouter un joueur
        </button>
        <button class="btn ml-3 col-3 text-white"
                onclick="window.location.href='{{ url_for("session.add_game", session_id=session.id) }}';">
            Ajouter un jeu
        </button>
    </div>
    <h4 class="my-3">Jeux</h4>
        {% for game in games %}
            {% include "cards/game_card.html" %}
        {% endfor %}
    <h4 class="my-3">Joueurs ({{ session.nb_players_required }}/{{ session.players.count() }})</h4>
    <div class="users-list row">
        {% for item in players %}
            {% include "cards/user_card.html" %}
        {% endfor %}
    </div>
</main>
{% endblock %}

app/games/session/templates/sessions.html
{% extends "index.html" %}
{% block main %}
<main class="container-fluid col-9 mb-5 my-auto">
    <h2 class="text-center mb-5">{{ title }}</h2>

    <form class="my-5 mx-auto" action="{{ url_for('session.sessions') }}" method="POST">
        {{ form.hidden_tag() }}
        <div class="input-group">
            {{ form.sessions_hint }}
            {{ form.display_search_type }}
            <div class="input-group-append" id="search-buttons">
                <button class="btn show-advanced-search" type="button" data-toggle="collapse"
                        data-target="#advanced-search" aria-expanded="false" aria-controls="advanced-search"
                        title="Recherche avancée">
                    <i class="fa fa-sliders" aria-hidden="true"></i>
                </button>
                <button type="submit" class="btn btn-primary" title="Recherche">
                    <i class="fa fa-search" aria-hidden="true"></i>
                </button>
            </div>
        </div>
        <div class="collapse" id="advanced-search">
            <div class="card card-body">
                <h5 id="advanced-search-title" class="card-title">Recherche avancée</h5>
                {{ form.display_search_parameter.label }} {{ form.display_search_parameter }}
                <p>{{ form.sort_order.label }} {{ form.sort_order }}</p>
            </div>
        </div>
    </form>
    {% if sessions.pagination.items %}
        <div class="row">
            {% for session in sessions.pagination.items %}
                {% include "cards/session_card.html" %}
            {% endfor %}
        </div>
    {% endif %}
    <nav>
        <ul class="pagination mt-4 mb-0 mx-auto">
            {% if sessions.pagination.page == 1 %}
                <li class="page-item disabled">
                    <a class="page-link"
                       href="{{ url_for("session.sessions", page=sessions.pagination.prev_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                        &laquo;
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link"
                       href="{{ url_for("session.sessions", page=sessions.pagination.prev_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                        &laquo;
                    </a>
                </li>
            {% endif %}
            {% for page_num in sessions.pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if sessions.pagination.page == page_num %}
                        <li class="page-item active">
                            <a class="page-link"
                               href="{{ url_for("session.sessions", page=page_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                                {{ page_num }}
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{{ url_for("session.sessions", page=page_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                                {{ page_num }}
                            </a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link"
                           href="{{ url_for("session.sessions", page=sessions.prev_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                            ...
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if sessions.pagination.page == sessions.pagination.pages %}
                <li class="page-item disabled">
                    <a class="page-link"
                        href="{{ url_for("session.sessions", page=sessions.pagination.next_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                        &raquo;
                    </a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link"
                        href="{{ url_for("session.sessions", page=sessions.pagination.next_num, searchParameter=form.display_search_parameter.data, type=form.display_search_type.data, sessions=form.sessions_hint.data, sort_order=form.sort_order.data) }}">
                        &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
</main>
{% endblock %}